// prisma/conquistas-data.ts

export const conquistasData = [
  // 🟢 1. INÍCIO E ENGAJAMENTO
  { key: 'first_simulado', nome: 'Primeiro Acionamento', desc: 'Concluiu seu primeiro simulado no sistema.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 10 },
  { key: 'energizado_3d', nome: 'Energizado', desc: 'Realizou simulados por 3 dias seguidos.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'sinal_estavel_7d', nome: 'Sinal Estável', desc: 'Realizou simulados por 7 dias seguidos.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 25 },
  { key: 'corrente_continua_15d', nome: 'Corrente Contínua', desc: 'Realizou simulados por 15 dias seguidos.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 40 },
  { key: 'em_operacao_30d', nome: 'Em Operação', desc: 'Realizou simulados por 30 dias seguidos.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 60 },
  { key: 'bimestre_ativo_60d', nome: 'Bimestre Ativo', desc: 'Realizou simulados por 60 dias seguidos.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 100 },
  { key: 'trimestre_ativo_90d', nome: 'Trimestre Ativo', desc: 'Realizou simulados por 90 dias seguidos.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 120 },
  { key: 'quadrimestre_120d', nome: 'Quadrimestre de Dedicação', desc: 'Realizou simulados por 120 dias seguidos.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 140 },
  { key: 'semestre_plantao_180d', nome: 'Semestre de Plantão', desc: 'Realizou simulados por 180 dias seguidos.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 200 },
  { key: 'trimestre_triplo_270d', nome: 'Nove Meses de Persistência', desc: 'Realizou simulados por 270 dias seguidos.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 280 },
  { key: 'ano_runtime_365d', nome: 'Ano em Runtime', desc: 'Realizou simulados por 365 dias seguidos sem interrupção.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 500 },
  { key: 'ano_meio_540d', nome: 'Um Ano e Meio de Operação', desc: 'Realizou simulados por 540 dias seguidos.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 650 },
  { key: 'bienio_automacao_730d', nome: 'Biênio de Automação', desc: 'Realizou simulados por 730 dias seguidos (2 anos).', raridade: 'LENDARIO', cat: 'INICIO_ENGAJAMENTO', pts: 1000 },
  
  // Volume de Questões
  { key: 'primeira_leitura', nome: 'Primeira Leitura', desc: 'Respondeu suas primeiras 10 questões.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 10 },
  { key: 'logica_contatos_50q', nome: 'Lógica de Contatos', desc: 'Respondeu 50 questões no total.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 20 },
  { key: 'centenario_automacao_100q', nome: 'Centenário da Automação', desc: 'Respondeu 100 questões no total.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 30 },
  { key: 'duzentas_questoes', nome: 'Duzentas Leituras', desc: 'Respondeu 200 questões no total.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 45 },
  { key: 'meio_milhar_500q', nome: 'Meio Milhar', desc: 'Respondeu 500 questões no total.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 70 },
  { key: 'kilo_questao_1k', nome: 'Kilo-Questão', desc: 'Respondeu 1.000 questões no total.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 150 },
  { key: 'duas_mil_questoes', nome: 'Dois Mil Registros', desc: 'Respondeu 2.000 questões no total.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 220 },
  { key: 'mega_questao_5k', nome: 'Mega-Questão', desc: 'Respondeu 5.000 questões no total.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 400 },
  { key: 'giga_questao_10k', nome: 'Giga-Questão', desc: 'Respondeu 10.000 questões no total.', raridade: 'LENDARIO', cat: 'INICIO_ENGAJAMENTO', pts: 800 },
  { key: 'vinte_mil_questoes', nome: 'Banco Robusto', desc: 'Respondeu 20.000 questões no total.', raridade: 'LENDARIO', cat: 'INICIO_ENGAJAMENTO', pts: 1200 },
  { key: 'escalabilidade_50k', nome: 'Escalabilidade', desc: 'Respondeu 50.000 questões no total.', raridade: 'LENDARIO', cat: 'INICIO_ENGAJAMENTO', pts: 1500 },
  { key: 'banco_infinito_100k', nome: 'Banco de Dados Infinito', desc: 'Respondeu 100.000 questões no total.', raridade: 'MITICO', cat: 'INICIO_ENGAJAMENTO', pts: 3000 },

  // Horários e Turnos
  { key: 'turno_manha_1', nome: 'Turno da Manhã', desc: 'Concluiu um simulado entre 05:00 e 08:00.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'turno_manha_7', nome: 'Rotina Matinal', desc: 'Concluiu 7 simulados entre 05:00 e 08:00.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 35 },
  { key: 'turno_manha_30', nome: 'Madrugador Dedicado', desc: 'Concluiu 30 simulados entre 05:00 e 08:00.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 90 },
  { key: 'turno_manha_90', nome: 'Mestre do Amanhecer', desc: 'Concluiu 90 simulados entre 05:00 e 08:00.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 250 },
  { key: 'pausa_calibracao_1', nome: 'Pausa para Calibração', desc: 'Concluiu um simulado entre 12:00 e 13:30.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'pausa_calibracao_7', nome: 'Almoço Técnico', desc: 'Concluiu 7 simulados entre 12:00 e 13:30.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 35 },
  { key: 'pausa_calibracao_30', nome: 'Intervalo Produtivo', desc: 'Concluiu 30 simulados entre 12:00 e 13:30.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 90 },
  { key: 'pausa_calibracao_90', nome: 'Otimização de Pausa', desc: 'Concluiu 90 simulados entre 12:00 e 13:30.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 250 },
  { key: 'turno_noite_1', nome: 'Turno da Noite', desc: 'Concluiu um simulado entre 19:00 e 22:00.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'turno_noite_7', nome: 'Estudo Noturno', desc: 'Concluiu 7 simulados entre 19:00 e 22:00.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 35 },
  { key: 'turno_noite_30', nome: 'Plantão Noturno', desc: 'Concluiu 30 simulados entre 19:00 e 22:00.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 90 },
  { key: 'turno_noite_90', nome: 'Guardião da Noite', desc: 'Concluiu 90 simulados entre 19:00 e 22:00.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 250 },
  { key: 'manutencao_madrugada_1', nome: 'Manutenção de Madrugada', desc: 'Concluiu um simulado entre 00:00 e 04:59.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 40 },
  { key: 'manutencao_madrugada_7', nome: 'Operador de Madrugada', desc: 'Concluiu 7 simulados entre 00:00 e 04:59.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 100 },
  { key: 'manutencao_madrugada_30', nome: 'Vigilante Técnico', desc: 'Concluiu 30 simulados entre 00:00 e 04:59.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 280 },
  { key: 'hora_extra_sabado', nome: 'Hora Extra', desc: 'Realizou 5 simulados em um único sábado.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 35 },
  { key: 'sabado_dedicado_10', nome: 'Sábado Dedicado', desc: 'Realizou 10 sábados com pelo menos 3 simulados cada.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 110 },
  { key: 'sabado_dedicado_30', nome: 'Fim de Semana Técnico', desc: 'Realizou 30 sábados com pelo menos 3 simulados cada.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 300 },
  { key: 'domingo_fabrica', nome: 'Domingo de Fábrica', desc: 'Realizou 3 simulados em um domingo.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 35 },
  { key: 'domingo_dedicado_10', nome: 'Domingo Produtivo', desc: 'Realizou 10 domingos com pelo menos 2 simulados cada.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 110 },
  { key: 'domingo_dedicado_30', nome: 'Domingo da Automação', desc: 'Realizou 30 domingos com pelo menos 2 simulados cada.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 300 },
  
  // Perfil e Configurações (SEM SOCIAL)
  { key: 'entrada_digital', nome: 'Entrada Digital', desc: 'Completou todos os dados do seu perfil de aluno.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 10 },
  { key: 'ihm_personalizada', nome: 'IHM Personalizada', desc: 'Alterou o tema ou as cores da sua interface de estudo.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 10 },
  { key: 'primeira_variavel', nome: 'Primeira Variável', desc: 'Marcou sua primeira questão como "favorita".', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 5 },
  { key: 'log_erros', nome: 'Log de Erros', desc: 'Revisou sua primeira questão errada através do histórico.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 10 },
  { key: 'backup_conhecimento', nome: 'Backup de Conhecimento', desc: 'Exportou um relatório de desempenho em PDF.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'backup_mensal', nome: 'Backup Mensal', desc: 'Exportou relatórios de desempenho por 6 meses seguidos.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 50 },
  { key: 'sincronismo_multi', nome: 'Sincronismo Multiplataforma', desc: 'Logou no sistema via Desktop e Mobile no mesmo dia.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 20 },
  { key: 'sincronismo_semanal', nome: 'Sincronismo Semanal', desc: 'Logou via Desktop e Mobile no mesmo dia por 7 dias seguidos.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 45 },
  { key: 'leitor_manuais', nome: 'Leitor de Manuais', desc: 'Acessou a aba de materiais de apoio ou documentos técnicos.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 10 },
  
  // Ciclos de Estudo (REBALANCEADO - Anti-Farm para curtos, Valorização para longos)
  { key: 'ciclo_curto_5q', nome: 'Estudante de Ciclo Curto', desc: 'Concluiu 5 simulados de 5 questões em 24h.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 }, 
  { key: 'ciclo_medio_10q', nome: 'Ciclo Médio', desc: 'Concluiu 5 simulados de 10 questões em 24h.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 40 }, 
  { key: 'ciclo_longo_50q', nome: 'Estudante de Ciclo Longo', desc: 'Concluiu 2 simulados de 50 questões em 24h.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 150 }, 
  
  { key: 'maratona_projetos_3uc', nome: 'Maratona de Projetos', desc: 'Realizou simulados de 3 Unidades Curriculares diferentes no mesmo dia.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 45 },
  { key: 'maratona_projetos_5uc', nome: 'Multidisciplinar', desc: 'Realizou simulados de 5 Unidades Curriculares diferentes no mesmo dia.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 80 },
  { key: 'frequencia_modulada', nome: 'Frequência Modulada', desc: 'Entrou no sistema 7 dias seguidos, mesmo sem fazer simulados.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'frequencia_modulada_30', nome: 'Presença Constante', desc: 'Entrou no sistema 30 dias seguidos.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 50 },
  { key: 'alta_disponibilidade', nome: 'Alta Disponibilidade', desc: 'Manteve o aplicativo aberto/logado por mais de 5 horas em um dia.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 30 },
  { key: 'explorador_funcoes', nome: 'Explorador de Funções', desc: 'Navegou por todas as abas do sistema.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'primeira_revisao', nome: 'Primeira Revisão', desc: 'Revisou um simulado já concluído.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 10 },
  { key: 'versao_1_0', nome: 'Versão 1.0', desc: 'Completou o seu primeiro mês desde a data de cadastro.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 20 },
  { key: 'versao_2_0', nome: 'Versão 2.0', desc: 'Completou um ano de cadastro no sistema.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 150 },
  { key: 'legado_automacao', nome: 'Legado de Automação', desc: 'Completou dois anos de cadastro no sistema.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 350 },
  { key: 'aspirante_instrumentacao', nome: 'Aspirante de Instrumentação', desc: 'Alcançou o nível 5 de experiência.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 20 },
  { key: 'tecnico_treinamento', nome: 'Técnico em Treinamento', desc: 'Alcançou o nível 15 de experiência.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 50 },
  { key: 'tecnico_qualificado', nome: 'Técnico Qualificado', desc: 'Alcançou o nível 30 de experiência.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 100 },
  { key: 'operador_senior', nome: 'Operador Sênior', desc: 'Alcançou o nível 50 de experiência.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 150 },
  { key: 'especialista_processos', nome: 'Especialista de Processos', desc: 'Alcançou o nível 100 de experiência.', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 400 },
  { key: 'iniciante_veloz', nome: 'Iniciante Veloz', desc: 'Desbloqueou 5 conquistas nas primeiras 2 horas após o cadastro.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 25 },
  { key: 'estudo_transicao', nome: 'Estudo de Transição', desc: 'Realizou um simulado durante a virada do ano (Réveillon).', raridade: 'EPICO', cat: 'INICIO_ENGAJAMENTO', pts: 300 },
  { key: 'feriado_painel_ligado', nome: 'Feriado com Painel Ligado', desc: 'Realizou simulados em 3 feriados nacionais diferentes.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 60 },
  { key: 'coletor_dados_18uc', nome: 'Coletor de Dados', desc: 'Respondeu questões de todas as 18 Unidades Curriculares disponíveis.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 200 },
  { key: 'sinal_vida', nome: 'Sinal de Vida', desc: 'Realizou ao menos uma questão após 30 dias de inatividade.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 10 },
  { key: 'fanatico_resultados', nome: 'Fanático por Resultados', desc: 'Verificou sua posição no ranking global 20 vezes em uma semana.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'analista_kpis', nome: 'Analista de KPIs', desc: 'Analisou seus gráficos de desempenho por mais de 10 minutos.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'atestado_qualidade', nome: 'Atestado de Qualidade', desc: 'Obteve sua primeira insígnia de "Nota Máxima" em um simulado de UC. (Incomum)', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 50 },
  { key: 'loop_estudo', nome: 'Loop de Estudo', desc: 'Refez o mesmo simulado 3 vezes até atingir 100%.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 20 },
  { key: 'rotina_3_7d', nome: 'Rotina Iniciada', desc: 'Realizou 3 simulados em 7 dias.', raridade: 'COMUM', cat: 'INICIO_ENGAJAMENTO', pts: 15 },
  { key: 'maratona_5_30d', nome: 'Maratona Básica', desc: 'Realizou 5 simulados em 30 dias.', raridade: 'INCOMUM', cat: 'INICIO_ENGAJAMENTO', pts: 25 },
  { key: 'maratona_pro_10_60d', nome: 'Maratona Pro', desc: 'Realizou 10 simulados em 60 dias.', raridade: 'RARO', cat: 'INICIO_ENGAJAMENTO', pts: 50 },

  // 🟡 2. PERFORMANCE E VELOCIDADE (REBALANCEADO)
  { key: 'set_point_perfeito', nome: 'Set Point Perfeito', desc: 'Acertou 100% de um simulado com mais de 20 questões.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 250 },
  { key: 'set_point_5q', nome: 'Perfeição em 5', desc: 'Acertou 100% em um simulado de 5 questões.', raridade: 'COMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 10 }, 
  { key: 'set_point_10q', nome: 'Perfeição em 10', desc: 'Acertou 100% em um simulado de 10 questões.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 25 }, 
  { key: 'set_point_30q', nome: 'Perfeição em 30', desc: 'Acertou 100% em um simulado de 30 questões.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 150 }, 
  { key: 'set_point_50q', nome: 'Perfeição em 50', desc: 'Acertou 100% em um simulado de 50 questões.', raridade: 'LENDARIO', cat: 'PERFORMANCE_VELOCIDADE', pts: 500 }, 

  { key: 'dentro_tolerancia', nome: 'Dentro da Tolerância', desc: 'Manteve média superior a 90% em um bloco de 50 questões.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 120 },
  { key: 'execucao_veloz', nome: 'Execução Veloz', desc: 'Terminou um simulado de 20 questões em menos de 5 minutos com nota > 80%.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 100 },
  { key: 'arranque_suave', nome: 'Arranque Suave', desc: 'Acertou as primeiras 15 questões de um simulado sem interrupções.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 50 },
  { key: 'nota_alta_90', nome: 'Nota Alta', desc: 'Alcançou nota >= 90% em um simulado.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 80 },
  { key: 'nota_alta_3x', nome: 'Consistência Superior', desc: 'Alcançou nota >= 90% em 3 simulados seguidos.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 110 },
  { key: 'media_estavel_85_5', nome: 'Sinal Estabilizado', desc: 'Manteve média > 85% em 5 simulados seguidos.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 120 },
  { key: 'media_estavel_85_10', nome: 'Estabilidade Plena', desc: 'Manteve média > 85% em 10 simulados seguidos.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 220 },
  { key: 'melhoria_15pct', nome: 'Otimização de Processo', desc: 'Aumentou média em 15% comparado ao mês anterior.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 40 },
  { key: 'melhoria_20pct', nome: 'Salto de Qualidade', desc: 'Aumentou média em 20% comparado ao mês anterior.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 50 },
  { key: 'recuperacao_watchdog', nome: 'Sistema de Recuperação', desc: 'Após 3 notas baixas (<60%), tirou um 100%.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 100 },
  { key: 'acertador_10_sequencia', nome: 'Sequência Básica', desc: 'Acertou 10 questões seguidas.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 40 },
  { key: 'acertador_20_sequencia', nome: 'Sequência Lógica', desc: 'Acertou 20 questões seguidas.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 130 },
  { key: 'acertador_30_sequencia', nome: 'Algoritmo Consistente', desc: 'Acertou 30 questões seguidas.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 180 },
  { key: 'acertador_50_sequencia', nome: 'Algoritmo Infalível', desc: 'Acertou 50 questões seguidas.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 300 },
  { key: 'sem_dicas_5', nome: 'Autonomia Técnica', desc: 'Concluiu 5 simulados sem usar nenhuma dica/ajuda.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 60 },
  { key: 'sem_dicas_10', nome: 'Modo Manual', desc: 'Concluiu 10 simulados sem usar nenhuma dica/ajuda.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 150 },
  { key: 'tempo_ouro_20pct', nome: 'Eficiência Temporal', desc: 'Finalizou com 20% do tempo sobrando.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 25 },
  { key: 'tempo_ouro_25pct', nome: 'Eficiência Energética', desc: 'Finalizou com 25% do tempo sobrando.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 30 },
  { key: 'tempo_ouro_30pct', nome: 'Otimização Avançada', desc: 'Finalizou com 30% do tempo sobrando.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 60 },
  { key: 'relampago_40pct', nome: 'Velocidade Controlada', desc: 'Finalizou com 40% do tempo sobrando.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 70 },
  { key: 'relampago_50pct', nome: 'Alta Velocidade', desc: 'Finalizou com 50% do tempo sobrando.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 80 },
  
  // Speed Runs (REBALANCEADO - 50q muito valorizado)
  { key: 'speed_5q_60s', nome: 'Ligeirinho (5q)', desc: '5 questões em < 60 segundos com > 80% de acerto.', raridade: 'COMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 15 },
  { key: 'speed_5q_30s', nome: 'Instante (5q)', desc: '5 questões em < 30 segundos com > 80% de acerto.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 40 },
  { key: 'speed_5q_25s', nome: 'Relâmpago (5q)', desc: '5 questões em < 25 segundos com 100% de acerto.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 90 },
  { key: 'speed_10q_2m', nome: 'Vupt (10q)', desc: '10 questões em < 2 minutos com > 80% de acerto.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 40 },
  { key: 'speed_10q_90s', nome: 'Veloz (10q)', desc: '10 questões em < 90 segundos com > 80% de acerto.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 55 },
  { key: 'speed_10q_1m', nome: 'Sônico (10q)', desc: '10 questões em < 60 segundos com > 80% de acerto.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 90 },
  { key: 'speed_10q_50s', nome: 'Supersônico (10q)', desc: '10 questões em < 50 segundos com 100% de acerto.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 200 },
  { key: 'speed_20q_5m', nome: 'Turbina (20q)', desc: '20 questões em < 5 minutos com > 80% de acerto.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 100 },
  { key: 'speed_20q_4m', nome: 'Turbo (20q)', desc: '20 questões em < 4 minutos com > 85% de acerto.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 130 },
  { key: 'speed_20q_3m', nome: 'Jato (20q)', desc: '20 questões em < 3 minutos com > 90% de acerto.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 200 },
  { key: 'speed_20q_2m', nome: 'Foguete (20q)', desc: '20 questões em < 2 minutos com 100% de acerto.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 280 },
  { key: 'speed_30q_10m', nome: 'Eficiência Industrial (30q)', desc: '30 questões em < 10 minutos com > 80% de acerto.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 110 },
  { key: 'speed_30q_8m', nome: 'Linha de Montagem (30q)', desc: '30 questões em < 8 minutos com > 85% de acerto.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 120 },
  { key: 'speed_30q_6m', nome: 'Produção Acelerada (30q)', desc: '30 questões em < 6 minutos com > 90% de acerto.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 210 },
  { key: 'speed_30q_5m', nome: 'Supercondutor (30q)', desc: '30 questões em < 5 minutos com > 90% de acerto.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 250 },
  
  // Speed 50q - Valorizado
  { key: 'speed_50q_20m', nome: 'Processamento em Lote (50q)', desc: '50 questões em < 20 minutos com > 80% de acerto.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 180 },
  { key: 'speed_50q_15m', nome: 'Produção em Massa (50q)', desc: '50 questões em < 15 minutos com > 85% de acerto.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 450 }, 
  { key: 'speed_50q_12m', nome: 'Linha Automatizada (50q)', desc: '50 questões em < 12 minutos com > 90% de acerto.', raridade: 'LENDARIO', cat: 'PERFORMANCE_VELOCIDADE', pts: 600 }, 
  { key: 'speed_50q_10m', nome: 'Foguete de Automação (50q)', desc: '50 questões em < 10 minutos com > 90% de acerto.', raridade: 'LENDARIO', cat: 'PERFORMANCE_VELOCIDADE', pts: 800 }, 
  { key: 'speed_40q_400s', nome: 'Ritmo de Fábrica', desc: '40 questões em 400 segundos (10s/q) com > 80% de acerto.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 300 },
  
  { key: 'constancia_tempo', nome: 'Relógio de Tempo Real', desc: 'Terminou 3 simulados com a mesma duração exata (±3 segundos).', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 150 },
  { key: 'decisao_rapida', nome: 'Tempo de Varredura', desc: 'Respondeu uma questão difícil em menos de 5 segundos e acertou.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 100 },
  { key: 'decisao_instantanea', nome: 'Processamento Imediato', desc: 'Respondeu 5 questões difíceis em menos de 5 segundos cada e acertou todas.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 280 },
  { key: 'maratona_1h', nome: 'Uma Hora de Dedicação', desc: 'Estudou por 1 hora ininterrupta no app.', raridade: 'COMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 25 },
  { key: 'maratona_2h', nome: 'Turno Dobrado', desc: 'Estudou por 2 horas ininterruptas no app.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 50 },
  { key: 'maratona_3h', nome: 'Três Horas Contínuas', desc: 'Estudou por 3 horas ininterruptas no app.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 100 },
  { key: 'maratona_5h', nome: 'Plantão Estendido', desc: 'Estudou por 5 horas ininterruptas no app.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 250 },
  { key: 'top_semana', nome: 'First Out (Semana)', desc: 'Top 10% da leaderboard semanal.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 80 },
  { key: 'top_semana_3x', nome: 'Dominância Semanal', desc: 'Top 10% da leaderboard semanal por 3 semanas seguidas.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 150 },
  { key: 'top_mes', nome: 'Mestre da Planta (Mês)', desc: 'Top 5% da leaderboard mensal.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 200 },
  { key: 'top_mes_3x', nome: 'Hegemonia Mensal', desc: 'Top 5% da leaderboard mensal por 3 meses seguidos.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 400 },
  { key: 'rank_1_dia', nome: 'Operador do Dia', desc: 'Ser #1 no ranking diário.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 150 },
  { key: 'rank_1_dia_3x', nome: 'Tricampeão Diário', desc: 'Ser #1 no ranking diário por 3 vezes.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 250 },
  { key: 'rank_1_semana', nome: 'Líder Semanal', desc: 'Ser #1 no ranking semanal.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 300 },
  { key: 'rank_1_mes', nome: 'Campeão Mensal', desc: 'Ser #1 no ranking mensal.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 450 },
  { key: 'rank_1_total', nome: 'Gerente Geral', desc: 'Alcançar o #1 no ranking global histórico. (Lendário)', raridade: 'LENDARIO', cat: 'PERFORMANCE_VELOCIDADE', pts: 800 },
  { key: 'precisao_cirurgica', nome: 'Calibração RBC', desc: 'Acertar 10 questões de nível "Difícil" seguidas sem errar.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 120 },
  { key: 'precisao_extrema', nome: 'Precisão Milimétrica', desc: 'Acertar 20 questões de nível "Difícil" seguidas sem errar.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 280 },
  { key: 'analista_de_dados', nome: 'Supervisório Humano', desc: 'Revisar o relatório de desempenho 10 vezes.', raridade: 'COMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 10 },
  { key: 'dez_simulados', nome: 'Dez Simulados', desc: 'Completou 10 simulados totais.', raridade: 'COMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 20 },
  { key: 'vinte_simulados', nome: 'Vinte Simulados', desc: 'Completou 20 simulados totais.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 35 },
  { key: 'cinquenta_simulados', nome: 'Cinquenta Simulados', desc: 'Completou 50 simulados totais.', raridade: 'INCOMUM', cat: 'PERFORMANCE_VELOCIDADE', pts: 60 },
  { key: 'cem_simulados', nome: 'Cem Simulados', desc: 'Completou 100 simulados totais.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 150 },
  { key: 'duzentos_simulados', nome: 'Duzentos Simulados', desc: 'Completou 200 simulados totais.', raridade: 'EPICO', cat: 'PERFORMANCE_VELOCIDADE', pts: 280 },

  // 🔵 3. MAESTRIA POR UNIDADE CURRICULAR
  { key: 'master_eletro', nome: 'Eletricista de Manutenção', desc: 'Dominar UC Fundamentos de Eletroeletrônica (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'expert_eletro', nome: 'Expert em Eletroeletrônica', desc: 'Dominar UC Fundamentos de Eletroeletrônica (média ≥ 95% em 20 simulados).', raridade: 'EPICO', cat: 'MAESTRIA_UC', pts: 250 },
  { key: 'master_clp', nome: 'Programador de Elite', desc: 'Dominar UC Sistemas Lógicos Programáveis (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'expert_clp', nome: 'Mestre CLP', desc: 'Dominar UC Sistemas Lógicos Programáveis (média ≥ 95% em 20 simulados).', raridade: 'EPICO', cat: 'MAESTRIA_UC', pts: 250 },
  { key: 'master_instru', nome: 'Instrumentista de Campo', desc: 'Dominar UC Instrumentação e Controle (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'expert_instru', nome: 'Expert em Instrumentação', desc: 'Dominar UC Instrumentação e Controle (média ≥ 95% em 20 simulados).', raridade: 'EPICO', cat: 'MAESTRIA_UC', pts: 250 },
  { key: 'master_pneumo', nome: 'Mestre da Pressão', desc: 'Dominar UC Sistemas Eletrohidráulicos e Eletropneumáticos (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_desenho', nome: 'Projetista de Diagramas', desc: 'Dominar UC Desenho Técnico Aplicado (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_redes', nome: 'Arquiteto de Redes', desc: 'Dominar UC Comunicação e Informática Aplicada (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_manutencao', nome: 'Preditiva Humana', desc: 'Dominar UC Manutenção de Sistemas Automatizados (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_supervisorio', nome: 'Olho do Mestre', desc: 'Dominar UC Sistemas de Supervisão e Controle (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_micro', nome: 'Coração do Sistema', desc: 'Dominar UC Sistemas Eletrônicos e Microcontrolados (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_comissionamento', nome: 'Start-up Sucesso', desc: 'Dominar UC Comissionamento de Sistemas (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_acionamentos', nome: 'Mestre dos Motores', desc: 'Dominar UC Acionamentos Eletroeletrônicos (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_gestao', nome: 'Gestor de Projetos', desc: 'Dominar UC Gestão dos Processos de Implementação (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_logica', nome: 'Mente Booleana', desc: 'Dominar UC Lógica de Programação (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_intertravamento', nome: 'Segurança em Primeiro Lugar', desc: 'Dominar UC Projetos de Intertravamento (NR12) (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_integracao', nome: 'Integrador de Sistemas', desc: 'Dominar UC Integração de Dispositivos (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_proj_aciona', nome: 'Projetista de Acionamentos', desc: 'Dominar UC Projetos de Acionamentos (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_proj_controle', nome: 'Controlador Mestre', desc: 'Dominar UC Projetos de Controle (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'master_desenvolvimento', nome: 'Desenvolvedor de Projetos', desc: 'Dominar UC Desenvolvimento de Projetos (média ≥ 85% em 10 simulados).', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'full_course', nome: 'Técnico Formado', desc: 'Completar 100% de todas as UCs do curso com média ≥ 70%.', raridade: 'LENDARIO', cat: 'MAESTRIA_UC', pts: 700 },
  { key: 'full_course_expert', nome: 'Técnico Expert', desc: 'Completar 100% de todas as UCs do curso com média ≥ 85%.', raridade: 'LENDARIO', cat: 'MAESTRIA_UC', pts: 1000 },
  { key: 'especialista_multidisciplinar', nome: 'Interoperabilidade', desc: 'Nota > 90% em um simulado que misture 5 UCs diferentes.', raridade: 'EPICO', cat: 'MAESTRIA_UC', pts: 250 },
  { key: 'base_solida', nome: 'Fundamentos de Aço', desc: 'Acertar todas as questões de UCs Introdutórias (Fundamentos de Eletroeletrônica).', raridade: 'INCOMUM', cat: 'MAESTRIA_UC', pts: 50 },
  { key: 'uc_completa_3', nome: 'Três Unidades Dominadas', desc: 'Completar 3 UCs com média ≥ 85%.', raridade: 'INCOMUM', cat: 'MAESTRIA_UC', pts: 70 },
  { key: 'uc_completa_5', nome: 'Cinco Unidades Dominadas', desc: 'Completar 5 UCs com média ≥ 85%.', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 130 },
  { key: 'uc_completa_10', nome: 'Dez Unidades Dominadas', desc: 'Completar 10 UCs com média ≥ 85%.', raridade: 'EPICO', cat: 'MAESTRIA_UC', pts: 300 },
  { key: 'uc_perfeita_1', nome: 'Unidade Perfeita', desc: 'Completar 1 UC com média = 100%.', raridade: 'EPICO', cat: 'MAESTRIA_UC', pts: 280 },
  { key: 'uc_perfeita_3', nome: 'Três Perfeições', desc: 'Completar 3 UCs com média = 100%.', raridade: 'LENDARIO', cat: 'MAESTRIA_UC', pts: 600 },
  { key: 'diversidade_uc_7d', nome: 'Variedade Semanal', desc: 'Estudar 7 UCs diferentes em 7 dias.', raridade: 'INCOMUM', cat: 'MAESTRIA_UC', pts: 45 },
  { key: 'diversidade_uc_30d', nome: 'Variedade Mensal', desc: 'Estudar 15 UCs diferentes em 30 dias.', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 110 },
  { key: 'foco_uc_30d', nome: 'Foco Disciplinar', desc: 'Estudar apenas 1 UC por 30 dias consecutivos.', raridade: 'INCOMUM', cat: 'MAESTRIA_UC', pts: 50 },
  { key: 'implementacao_f1', nome: 'Mestre da Implementação (F1)', desc: 'Concluir todos os simulados relacionados à Função 1.', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 150 },
  { key: 'manutencao_f2', nome: 'Analista de Manutenção (F2)', desc: 'Concluir todos os simulados relacionados à Função 2.', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 150 },
  { key: 'projetos_f3', nome: 'Engenho de Projetos (F3)', desc: 'Concluir todos os simulados relacionados à Função 3.', raridade: 'EPICO', cat: 'MAESTRIA_UC', pts: 300 },
  { key: 'tres_funcoes', nome: 'Técnico Completo', desc: 'Dominar as 3 Funções (F1, F2, F3) com média ≥ 85% em cada.', raridade: 'LENDARIO', cat: 'MAESTRIA_UC', pts: 750 },
  { key: 'subfuncao_1_1', nome: 'Especialista em Instalação Eletrônica', desc: 'Dominar Subfunção 1.1 com média ≥ 90%.', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'subfuncao_2_4', nome: 'Mestre do Comissionamento', desc: 'Dominar Subfunção 2.4 com média ≥ 90%.', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },
  { key: 'subfuncao_3_5', nome: 'Especialista em Segurança', desc: 'Dominar Subfunção 3.5 com média ≥ 90%.', raridade: 'RARO', cat: 'MAESTRIA_UC', pts: 100 },

  // 🟣 4. OBJETOS DE CONHECIMENTO E CAPACIDADES
  { key: 'expert_sensores', nome: 'Detector de Sinais', desc: '50 questões sobre Sensores com ≥90% de acerto.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 50 },
  { key: 'master_sensores', nome: 'Mestre dos Sensores', desc: '100 questões sobre Sensores com ≥95% de acerto.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 120 },
  { key: 'expert_clp_logic', nome: 'Lógica Ladder', desc: 'Acertar 30 questões de lógica de programação CLP.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 50 },
  { key: 'master_clp_logic', nome: 'Programador Ladder Expert', desc: 'Acertar 100 questões de lógica de programação CLP com ≥90% de acerto.', raridade: 'EPICO', cat: 'OBJETO_CONHECIMENTO', pts: 220 },
  { key: 'expert_nr12', nome: 'Guardião da Norma', desc: 'Acertar 20 questões sobre NR12/Segurança.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 45 },
  { key: 'master_nr12', nome: 'Auditor de Segurança', desc: 'Acertar 50 questões sobre NR12/Segurança com ≥95% de acerto.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 130 },
  { key: 'expert_redes_ind', nome: 'Protocolo Ativo', desc: 'Acertar 30 questões de Profibus/Profinet/Modbus.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 90 },
  { key: 'master_redes_ind', nome: 'Arquiteto de Protocolos', desc: 'Acertar 80 questões de Redes Industriais com ≥90% de acerto.', raridade: 'EPICO', cat: 'OBJETO_CONHECIMENTO', pts: 250 },
  { key: 'expert_multimetro', nome: 'Medição Real', desc: 'Acertar 20 questões de Instrumentos de Medição.', raridade: 'COMUM', cat: 'OBJETO_CONHECIMENTO', pts: 25 },
  { key: 'expert_diagramas', nome: 'Leitor de Plantas', desc: 'Acertar 20 questões de Simbologia e Diagramas.', raridade: 'COMUM', cat: 'OBJETO_CONHECIMENTO', pts: 25 },
  { key: 'master_diagramas', nome: 'Interpretador de Plantas', desc: 'Acertar 60 questões de Simbologia e Diagramas com ≥90% de acerto.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 110 },
  { key: 'expert_pid', nome: 'Sintonizador PID', desc: 'Acertar 15 questões de Malha de Controle.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 100 },
  { key: 'master_pid', nome: 'Mestre do Controle PID', desc: 'Acertar 40 questões de Malha de Controle com ≥95% de acerto.', raridade: 'EPICO', cat: 'OBJETO_CONHECIMENTO', pts: 280 },
  { key: 'expert_inversores', nome: 'Frequência Variável', desc: 'Acertar 20 questões de Acionamento de Motores.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 50 },
  { key: 'master_inversores', nome: 'Especialista em Inversores', desc: 'Acertar 60 questões de Acionamento de Motores com ≥90% de acerto.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 140 },
  { key: 'expert_banco_dados', nome: 'DB Admin', desc: 'Acertar 15 questões de Banco de Dados/Historiadores.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 40 },
  
  // Capacidades
  { key: 'capacidade_c1', nome: 'Mestre da Matemática', desc: 'Validar Capacidade C1 com média ≥85% em 20 questões.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 40 },
  { key: 'capacidade_c2', nome: 'Interpretador de Circuitos', desc: 'Validar Capacidade C2 com média ≥85% em 20 questões.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 40 },
  { key: 'capacidade_c3', nome: 'Parametrizador', desc: 'Validar Capacidade C3 com média ≥85% em 20 questões.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 40 },
  { key: 'capacidade_c4', nome: 'Programador Lógico', desc: 'Validar Capacidade C4 com média ≥85% em 20 questões.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 80 },
  { key: 'capacidade_c5', nome: 'Analista de Manutenção', desc: 'Validar Capacidade C5 com média ≥85% em 20 questões.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 80 },
  { key: 'capacidade_c6', nome: 'Estruturador de Dados', desc: 'Validar Capacidade C6 com média ≥85% em 20 questões.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 80 },
  { key: 'capacidade_c7', nome: 'Analista Técnico', desc: 'Validar Capacidade C7 com média ≥85% em 20 questões.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 80 },
  { key: 'capacidade_c8', nome: 'Avaliador de Segurança', desc: 'Validar Capacidade C8 com média ≥85% em 20 questões.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 80 },
  { key: 'capacidade_c9', nome: 'Montador Especialista', desc: 'Validar Capacidade C9 com média ≥85% em 20 questões.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 80 },
  { key: 'capacidade_c10', nome: 'Mestre dos Testes', desc: 'Validar Capacidade C10 com média ≥85% em 20 questões.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 100 },
  { key: 'todas_capacidades', nome: 'Dez Capacidades Dominadas', desc: 'Validar todas as 10 Capacidades com média ≥85%.', raridade: 'LENDARIO', cat: 'OBJETO_CONHECIMENTO', pts: 700 },
  
  { key: 'expert_microcontroladores', nome: 'Escovador de Bits', desc: 'Acertar 30 questões de Microcontroladores.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 90 },
  { key: 'expert_hidraulica', nome: 'Poder dos Fluidos', desc: 'Acertar 20 questões de Hidráulica.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 50 },
  { key: 'expert_scada', nome: 'Mestre do Supervisório', desc: 'Acertar 30 questões de IHM/SCADA.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 90 },
  { key: 'master_scada', nome: 'Especialista em SCADA', desc: 'Acertar 70 questões de IHM/SCADA com ≥90% de acerto.', raridade: 'EPICO', cat: 'OBJETO_CONHECIMENTO', pts: 250 },
  { key: 'analista_infra', nome: 'Infraestruturista', desc: 'Acertar 20 questões de Infra de Automação.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 40 },
  { key: 'expert_ajuste', nome: 'Ajuste Fino', desc: 'Acertar 15 questões de Parametrização.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 85 },
  { key: 'expert_documentacao', nome: 'Bibliotecário Técnico', desc: 'Acertar 20 questões de Documentação de Projetos.', raridade: 'COMUM', cat: 'OBJETO_CONHECIMENTO', pts: 20 },
  { key: 'metrologia_master', nome: 'Precisão Milimétrica', desc: 'Acertar 20 questões de Metrologia.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 30 },
  { key: 'expert_clp_avancado', nome: 'Lógica de Mestre', desc: 'Acertar 30 questões de Contadores e Temporizadores.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 100 },
  { key: 'norma_tecnica_pro', nome: 'Padronizado', desc: 'Acertar 30 questões de Normas Técnicas Aplicadas.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 60 },
  { key: 'resolutor_problemas', nome: 'Troubleshooting', desc: 'Acertar 10 questões de "Diagnóstico de Falhas".', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 110 },
  { key: 'expert_ca_cc', nome: 'Alternado e Contínuo', desc: 'Acertar 40 questões de Circuitos CA/CC.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 50 },
  { key: 'master_ca_cc', nome: 'Mestre dos Circuitos', desc: 'Acertar 100 questões de Circuitos CA/CC com ≥90% de acerto.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 140 },
  { key: 'expert_eletronica', nome: 'Semicondutores', desc: 'Acertar 30 questões de Componentes Eletrônicos.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 55 },
  { key: 'especial_prova', nome: 'Score de Corte', desc: 'Atingir nota de corte de um concurso real configurado.', raridade: 'EPICO', cat: 'OBJETO_CONHECIMENTO', pts: 200 },
  { key: 'questoes_dificeis_10', nome: 'Hard Mode', desc: 'Acertar 10 questões marcadas como "Difícil".', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 60 },
  { key: 'questoes_dificeis_20', nome: 'Expert em Difíceis', desc: 'Acertar 20 questões marcadas como "Difícil".', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 120 },
  { key: 'questoes_dificeis_50', nome: 'Dominador de Desafios', desc: 'Acertar 50 questões marcadas como "Difícil" com ≥80% de acerto.', raridade: 'EPICO', cat: 'OBJETO_CONHECIMENTO', pts: 300 },
  { key: 'caca_erros_10', nome: 'Debugador', desc: 'Acertar 10 questões que você errou anteriormente.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 35 },
  { key: 'caca_erros_20', nome: 'Corretor de Erros', desc: 'Acertar 20 questões que você errou anteriormente.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 50 },
  { key: 'caca_erros_50', nome: 'Mestre da Correção', desc: 'Acertar 50 questões que você errou anteriormente.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 110 },
  { key: 'revisao_inteligente_50', nome: 'Manutenção Preventiva', desc: 'Revisar 50 questões marcadas como favoritas.', raridade: 'INCOMUM', cat: 'OBJETO_CONHECIMENTO', pts: 30 },
  { key: 'revisao_inteligente_100', nome: 'Revisor Sistemático', desc: 'Revisar 100 questões marcadas como favoritas.', raridade: 'RARO', cat: 'OBJETO_CONHECIMENTO', pts: 80 },

  // 🟠 5. CONQUISTAS DE DESEMPENHO AVANÇADO
  { key: 'modo_pratico_5', nome: 'Modo Cronometrado', desc: 'Concluiu 5 simulados em modo cronometrado.', raridade: 'COMUM', cat: 'DESEMPENHO_AVANCADO', pts: 20 },
  { key: 'modo_pratico_10', nome: 'Modo Prático', desc: 'Concluiu 10 simulados em modo cronometrado.', raridade: 'INCOMUM', cat: 'DESEMPENHO_AVANCADO', pts: 35 },
  { key: 'modo_pratico_30', nome: 'Especialista Cronometrado', desc: 'Concluiu 30 simulados em modo cronometrado.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 90 },
  { key: 'modo_sem_pausa_3', nome: 'Sem Pausa', desc: 'Terminou 3 simulados sem pausas longas.', raridade: 'COMUM', cat: 'DESEMPENHO_AVANCADO', pts: 15 },
  { key: 'modo_sem_pausa_10', nome: 'Ciclo Contínuo', desc: 'Terminou 10 simulados sem pausar o cronômetro.', raridade: 'INCOMUM', cat: 'DESEMPENHO_AVANCADO', pts: 40 },
  { key: 'modo_sem_pausa_30', nome: 'Fluxo Ininterrupto', desc: 'Terminou 30 simulados sem pausar o cronômetro.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 110 },
  { key: 'resiliente_5', nome: 'Auto-Reset', desc: 'Após errar 5 seguidas, acertou as próximas 10.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 100 },
  { key: 'aprimoramento_10pct', nome: 'Melhoria Contínua', desc: 'Reduziu tempo médio por questão em 10% mantendo acurácia.', raridade: 'INCOMUM', cat: 'DESEMPENHO_AVANCADO', pts: 50 },
  { key: 'aprimoramento_15pct', nome: 'Kaizen', desc: 'Reduziu tempo médio por questão em 15% mantendo acurácia.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 110 },
  { key: 'aprimoramento_20pct', nome: 'Otimização Extrema', desc: 'Reduziu tempo médio por questão em 20% mantendo acurácia.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 220 },
  { key: 'precisao_90', nome: 'Alta Precisão', desc: 'Manter média > 90% em um bloco de 100 questões.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 130 },
  { key: 'precisao_95', nome: 'Alta Fidelidade', desc: 'Manter média > 95% em um bloco de 100 questões.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 250 },
  { key: 'precisao_98', nome: 'Precisão Cirúrgica', desc: 'Manter média > 98% em um bloco de 50 questões.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 280 },
  { key: 'viciado_estudo_4periodos', nome: 'Overclock', desc: 'Respondeu questões em 4 períodos diferentes do mesmo dia.', raridade: 'INCOMUM', cat: 'DESEMPENHO_AVANCADO', pts: 50 },
  { key: 'percurso_total', nome: 'Full Stack Técnico', desc: 'Completar todos os desafios de todas as UCs.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 500 },
  { key: 'zero_erros_3d', nome: 'Três Dias Perfeitos', desc: 'Passar 3 dias sem errar nenhuma questão (mín. 10/dia).', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 150 },
  { key: 'zero_erros_7d', nome: 'Sistema Infalível', desc: 'Passar 7 dias sem errar nenhuma questão (mín. 10/dia).', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 350 },
  { key: 'zero_erros_30d', nome: 'Mês Perfeito', desc: 'Passar 30 dias sem errar nenhuma questão (mín. 10/dia).', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 700 },
  { key: 'top_1_nacional', nome: 'Referência do Mercado', desc: 'Estar no Top 1% nacional.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 600 },
  { key: 'top_05_nacional', nome: 'Elite Nacional', desc: 'Estar no Top 0,5% nacional.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 800 },
  { key: 'resolutor_relampago_15s', nome: 'Tempo de Resposta', desc: 'Média de 15s por questão em simulado de 50q com nota > 80%.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 280 },
  { key: 'resolutor_relampago_10s', nome: 'Processador Veloz', desc: 'Média de 10s por questão em simulado de 50q com nota > 85%.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 350 },
  { key: 'mestre_simulados_200', nome: 'Duzentos Completos', desc: 'Concluir 200 simulados totais.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 350 },
  { key: 'mestre_simulados_500', nome: 'Homologado', desc: 'Concluir 500 simulados totais.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 700 },
  { key: 'mestre_simulados_1000', nome: 'Milésimo Simulado', desc: 'Concluir 1000 simulados totais.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 1200 },
  { key: 'quick_fix', nome: 'Manutenção Corretiva', desc: 'Acertar todas as questões que errou no dia anterior.', raridade: 'INCOMUM', cat: 'DESEMPENHO_AVANCADO', pts: 40 },
  { key: 'quick_fix_7d', nome: 'Correção Semanal', desc: 'Acertar todas as questões que errou na semana anterior.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 100 },
  { key: 'topic_master_5', nome: 'Especialista de Tópico', desc: '5 simulados seguidos com nota > 90% no mesmo tema.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 100 },
  { key: 'topic_master_10', nome: 'Domínio de Tópico', desc: '10 simulados seguidos com nota > 90% no mesmo tema.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 150 },
  { key: 'topic_master_20', nome: 'Autoridade em Tópico', desc: '20 simulados seguidos com nota > 90% no mesmo tema.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 300 },
  { key: '1000_acertos', nome: 'Mil Acertos', desc: 'Acumular 1.000 questões corretas.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 150 },
  { key: '5000_acertos', nome: 'Cinco Mil Acertos', desc: 'Acumular 5.000 questões corretas.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 400 },
  { key: '10000_acertos', nome: 'Dez Mil Acertos', desc: 'Acumular 10.000 questões corretas.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 700 },
  { key: '100_horas_estudo', nome: '100 Horas', desc: 'Acumular 100 horas estudadas.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 120 },
  { key: '500_horas_estudo', nome: '500 Horas', desc: 'Acumular 500 horas estudadas.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 450 },
  { key: '1000_horas_estudo', nome: 'Mil Horas de Dedicação', desc: 'Acumular 1.000 horas estudadas.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 800 },
  { key: 'recuperacao_rapida', nome: 'Recuperação Rápida', desc: 'Recuperou score de <50% para >70% em 3 semanas.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 100 },
  { key: 'recuperacao_extrema', nome: 'Recuperação Extrema', desc: 'Recuperou score de <40% para >85% em 1 mês.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 250 },
  { key: 'colecionador_10', nome: 'Colecionador', desc: 'Possui 10 conquistas diferentes.', raridade: 'COMUM', cat: 'DESEMPENHO_AVANCADO', pts: 20 },
  { key: 'colecionador_25', nome: 'Colecionador Dedicado', desc: 'Possui 25 conquistas diferentes.', raridade: 'INCOMUM', cat: 'DESEMPENHO_AVANCADO', pts: 60 },

  // NOVAS CONQUISTAS ANTI-FARM (Recompensam esforço real)
  { key: 'maratona_longa_10', nome: 'Resistência Técnica', desc: 'Completou 10 simulados de 50 questões.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 150 },
  { key: 'maratona_longa_50', nome: 'Maratonista', desc: 'Completou 50 simulados de 50 questões.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 800 },
  { key: 'maratona_longa_75', nome: 'Maratonista de Ferro', desc: 'Completou 75 simulados de 50 questões.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 1750 },
  { key: 'maratona_longa_100', nome: 'Ultraman', desc: 'Completou 100 simulados de 50 questões.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 4000 },
  { key: 'maratona_longa_150', nome: 'Ultraman Maníaco', desc: 'Completou 150 simulados de 50 questões.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 10000 },
  { key: 'maratona_longa_250', nome: 'Monsterman dos Simulados', desc: 'Completou 250 simulados de 50 questões.', raridade: 'MITICO', cat: 'DESEMPENHO_AVANCADO', pts: 25000 },
  { key: 'maratona_longa_400', nome: 'Aberração Monstruosa', desc: 'Completou 400 simulados de 50 questões.', raridade: 'MITICO', cat: 'DESEMPENHO_AVANCADO', pts: 60000 },

  // 🔵 8. MODO SAEP (Simulado Oficial) - [RECALIBRADO - TETO ~250 PTS]
  { key: 'saep_first_try', nome: 'Batismo de Fogo', desc: 'Concluiu seu primeiro Simulado SAEP completo (sem abandonar).', raridade: 'COMUM', cat: 'DESEMPENHO_AVANCADO', pts: 20 },
  { key: 'saep_bronze', nome: 'Aprovado no SAEP', desc: 'Obteve nota > 60% em um Simulado SAEP.', raridade: 'INCOMUM', cat: 'DESEMPENHO_AVANCADO', pts: 40 },
  { key: 'saep_silver', nome: 'Destaque no SAEP', desc: 'Obteve nota > 80% em um Simulado SAEP.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 80 },
  { key: 'saep_gold', nome: 'Excelência no SAEP', desc: 'Obteve nota > 95% em um Simulado SAEP.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 150 },
  { key: 'saep_survivor_5', nome: 'Sobrevivente', desc: 'Concluiu 5 Simulados SAEP sem nunca ter abandonado ou anulado uma prova.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 100 },
  { key: 'saep_consistency_10', nome: 'Veterano de Prova', desc: 'Concluiu 10 Simulados SAEP completos.', raridade: 'EPICO', cat: 'DESEMPENHO_AVANCADO', pts: 200 },
  { key: 'saep_speedster', nome: 'Eficiência sob Pressão', desc: 'Concluiu um Simulado SAEP (40q) em menos de 90 minutos com nota > 70%.', raridade: 'RARO', cat: 'PERFORMANCE_VELOCIDADE', pts: 120 },
  { key: 'saep_perfect', nome: 'Gabarito Oficial', desc: 'Acertou 40/40 questões em um Simulado SAEP.', raridade: 'LENDARIO', cat: 'DESEMPENHO_AVANCADO', pts: 350 },
  { key: 'saep_recovery', nome: 'Volta por Cima', desc: 'Após ter um simulado anulado ou abandonado, completou o próximo com nota > 80%.', raridade: 'RARO', cat: 'DESEMPENHO_AVANCADO', pts: 90 },

  // 🔴 6. CONQUISTAS OCULTAS
  { key: 'hidden_midnight_scholar', nome: 'O Fantasma da Fábrica', desc: 'Completar um simulado às exatas 03:07 da manhã.', raridade: 'MITICO', cat: 'OCULTA', pts: 1000, oculta: true },
  { key: 'hidden_serendipity', nome: 'Achei o Sinal!', desc: 'Clicar 10 vezes no logo da plataforma na tela de erro.', raridade: 'MITICO', cat: 'OCULTA', pts: 1200, oculta: true },
  { key: 'hidden_easter_egg', nome: 'Código Secreto', desc: 'Digitar uma sequência específica de teclas.', raridade: 'MITICO', cat: 'OCULTA', pts: 1500, oculta: true },
  { key: 'hidden_time_capsule', nome: 'De Volta ao Início', desc: 'Logar no dia do aniversário de fundação da plataforma.', raridade: 'MITICO', cat: 'OCULTA', pts: 2000, oculta: true },
  { key: 'hidden_focus_master', nome: 'Silêncio no Laboratório', desc: 'Ficar 1 hora com o simulado aberto sem trocar de aba.', raridade: 'MITICO', cat: 'OCULTA', pts: 1300, oculta: true },
  { key: 'hidden_lucky_7', nome: 'Sorte de Principiante', desc: 'Acertar a 7ª questão de 7 simulados seguidos.', raridade: 'EPICO', cat: 'OCULTA', pts: 1000, oculta: true },
  { key: 'hidden_perfect_fail', nome: 'Zero Absoluto', desc: 'Tirar 0% em um simulado de 30+ questões (errar todas).', raridade: 'EPICO', cat: 'OCULTA', pts: 1100, oculta: true },
  { key: 'hidden_legend_seed', nome: 'Semente da Lenda', desc: 'Desbloquear sua primeira conquista Impossível.', raridade: 'MITICO', cat: 'OCULTA', pts: 3000, oculta: true },
  { key: 'hidden_birthday_study', nome: 'Aniversário Técnico', desc: 'Realizar um simulado no dia do seu aniversário.', raridade: 'RARO', cat: 'OCULTA', pts: 800, oculta: true },
  { key: 'hidden_new_year', nome: 'Ano Novo, Estudos Novos', desc: 'Completar um simulado nos primeiros 5 minutos do ano novo.', raridade: 'EPICO', cat: 'OCULTA', pts: 1200, oculta: true },
  { key: 'hidden_palindrome', nome: 'Sequência Espelhada', desc: 'Completar um simulado em horário palíndromo.', raridade: 'RARO', cat: 'OCULTA', pts: 900, oculta: true },
  { key: 'hidden_sequential', nome: 'Sequência Numérica', desc: 'Acertar questões de números sequenciais em ordem.', raridade: 'EPICO', cat: 'OCULTA', pts: 1100, oculta: true },
  { key: 'hidden_observer', nome: 'Observador Silencioso', desc: 'Passar 30 minutos navegando sem clicar em nada relacionado a simulados.', raridade: 'INCOMUM', cat: 'OCULTA', pts: 500, oculta: true },

  // ⚫ 7. CONQUISTAS IMPOSSÍVEIS
  { key: 'imp_200s_40q', nome: 'Processador Quântico', desc: '40 questões em < 200 segundos com 100% de acerto.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 5000, impossivel: true, audit: true },
  { key: 'imp_101_percent', nome: 'Overflow de Sistema', desc: 'Alcançar 101% de progresso no curso.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 5000, impossivel: true, audit: true },
  { key: 'imp_time_traveler', nome: 'Viajante do Tempo', desc: 'Completar um simulado com data de finalização anterior à data de início.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 8000, impossivel: true, audit: true },
  { key: 'imp_infinite_loop', nome: 'Loop Infinito', desc: 'Responder 1.000.000 de questões.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 9999, impossivel: true, audit: true },
  { key: 'imp_perfect_year', nome: 'Ano Inabalável', desc: 'Média 100% em todos os dias de um ano bissexto.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 7500, impossivel: true, audit: true },
  { key: 'imp_one_second', nome: 'Sincronia Divina', desc: 'Concluir 10 simulados no exato mesmo segundo.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 6500, impossivel: true, audit: true },
  { key: 'imp_immortal', nome: 'Imortal da Automação', desc: 'Manter a conta ativa e com estudo diário por 27 anos.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 9000, impossivel: true, audit: true },
  { key: 'imp_every_question', nome: 'Omnisciente', desc: 'Acertar TODAS as questões existentes na base de dados.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 7000, impossivel: true, audit: true },
  { key: 'imp_god_mode', nome: 'Modo Deus', desc: 'Ativado apenas manualmente por administradores para testadores lendários.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 20000, impossivel: true, adminOnly: true, audit: true },
  { key: 'imp_phantom_perfect', nome: 'Fantasma Perfeito', desc: 'Ganhar todas as conquistas ocultas no primeiro dia de conta.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 10000, impossivel: true, audit: true },
  { key: 'imp_50q_100s', nome: 'Velocidade da Luz', desc: '50 questões em < 100 segundos com 100% de acerto.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 8000, impossivel: true, audit: true },
  { key: 'imp_zero_time', nome: 'Tempo Zero', desc: 'Completar um simulado com tempo de execução registrado como 0 segundos.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 7500, impossivel: true, audit: true },
  { key: 'imp_all_streaks', nome: 'Senhor dos Streaks', desc: 'Manter streaks de 365 dias em todas as categorias simultaneamente.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 9500, impossivel: true, audit: true },
  { key: 'imp_perfect_score_all', nome: 'Perfeição Universal', desc: 'Obter 100% de acerto em todos os simulados de todas as UCs.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 10000, impossivel: true, audit: true },
  { key: 'imp_simultaneous', nome: 'Processamento Paralelo', desc: 'Completar 5 simulados diferentes ao mesmo tempo.', raridade: 'MITICO', cat: 'IMPOSSIVEL', pts: 6000, impossivel: true, audit: true },
];