// prisma/data-auxiliares.ts

export const bancasData = [
    // As 5 Grandes ("Big Five")
    { codigo: 'BANCA-001', sigla: 'CEBRASPE', nome: 'Centro Brasileiro de Pesquisa em Avaliação e Seleção e de Promoção de Eventos (Cespe)' },
    { codigo: 'BANCA-002', sigla: 'CESGRANRIO', nome: 'Fundação Cesgranrio' },
    { codigo: 'BANCA-003', sigla: 'FGV', nome: 'Fundação Getúlio Vargas' },
    { codigo: 'BANCA-004', sigla: 'FCC', nome: 'Fundação Carlos Chagas' },
    { codigo: 'BANCA-005', sigla: 'VUNESP', nome: 'Fundação para o Vestibular da UNESP' },

    // Bancas de Médio/Grande Porte Nacionais
    { codigo: 'BANCA-006', sigla: 'IDECAN', nome: 'Instituto de Desenvolvimento Educacional, Cultural e Assistacional Nacional' },
    { codigo: 'BANCA-007', sigla: 'IBFC', nome: 'Instituto Brasileiro de Formação e Capacitação' },
    { codigo: 'BANCA-008', sigla: 'AOCP', nome: 'Instituto AOCP' },
    { codigo: 'BANCA-009', sigla: 'CONSULPLAN', nome: 'Consultoria e Planejamento em Administração Pública' },
    { codigo: 'BANCA-010', sigla: 'QUADRIX', nome: 'Instituto Quadrix' },
    { codigo: 'BANCA-011', sigla: 'IADES', nome: 'Instituto Americano de Desenvolvimento' },
    { codigo: 'BANCA-012', sigla: 'FUNDATEC', nome: 'Fundação Universidade Empresa de Tecnologia e Ciências' },
    { codigo: 'BANCA-013', sigla: 'FUMARC', nome: 'Fundação Mariana Resende Costa' },
    { codigo: 'BANCA-014', sigla: 'SELECON', nome: 'Instituto Selecon' },
    { codigo: 'BANCA-015', sigla: 'IBADE', nome: 'Instituto Brasileiro de Apoio e Desenvolvimento Executivo' },

    // Bancas Regionais e Específicas
    { codigo: 'BANCA-016', sigla: 'FAPEC', nome: 'Fundação de Apoio à Pesquisa, ao Ensino e à Cultura' },
    { codigo: 'BANCA-017', sigla: 'FAPEMS', nome: 'Fundação de Apoio à Pesquisa, ao Ensino e à Cultura de MS' },
    { codigo: 'BANCA-018', sigla: 'CETRO', nome: 'Cetro Concursos Públicos' },
    { codigo: 'BANCA-019', sigla: 'CKM', nome: 'CKM Serviços' },
    { codigo: 'BANCA-020', sigla: 'NOSSO RUMO', nome: 'Instituto de Educação e Desenvolvimento Social Nosso Rumo' },
    { codigo: 'BANCA-021', sigla: 'AVANÇA SP', nome: 'Avança SP' },
    { codigo: 'BANCA-022', sigla: 'VANGUARDA', nome: 'Instituto Vanguarda' },
    { codigo: 'BANCA-023', sigla: 'IGEDUC', nome: 'Instituto IGEDUC' },
    { codigo: 'BANCA-024', sigla: 'FUNRIO', nome: 'Fundação de Apoio a Pesquisa, Ensino e Assistência' },
    { codigo: 'BANCA-025', sigla: 'COPEVE', nome: 'Comissão Permanente do Vestibular' },
    
    // Bancas Universitárias e Estaduais
    { codigo: 'BANCA-026', sigla: 'COMPERVE', nome: 'Núcleo Permanente de Concursos (UFRN)' },
    { codigo: 'BANCA-027', sigla: 'NUCEPE', nome: 'Núcleo de Concursos e Promoção de Eventos (UESPI)' },
    { codigo: 'BANCA-028', sigla: 'UPENET', nome: 'Instituto de Apoio à Universidade de Pernambuco' },
    { codigo: 'BANCA-029', sigla: 'LEGALLE', nome: 'Legalle Concursos' },
    { codigo: 'BANCA-030', sigla: 'OBJETIVA', nome: 'Objetiva Concursos' },
    { codigo: 'BANCA-031', sigla: 'FEPESE', nome: 'Fundação de Estudos e Pesquisas Socioeconômicos' },
    { codigo: 'BANCA-032', sigla: 'FAURGS', nome: 'Fundação de Apoio da Universidade Federal do Rio Grande do Sul' },
    { codigo: 'BANCA-033', sigla: 'CEV-UECE', nome: 'Comissão Executiva do Vestibular da UECE' },
    { codigo: 'BANCA-034', sigla: 'COVEST', nome: 'Comissão de Processos Seletivos da UFPE' },
    { codigo: 'BANCA-035', sigla: 'NC-UFPR', nome: 'Núcleo de Concursos da UFPR' },

    // Bancas Menores e Municipais
    { codigo: 'BANCA-036', sigla: 'GS', nome: 'GS Assessoria e Consultoria' },
    { codigo: 'BANCA-037', sigla: 'MS CONCURSOS', nome: 'MS Concursos' },
    { codigo: 'BANCA-038', sigla: 'SARMENTO', nome: 'Sarmento Concursos' },
    { codigo: 'BANCA-039', sigla: 'METROCAPITAL', nome: 'MetroCapital Soluções' },
    { codigo: 'BANCA-040', sigla: 'INDEPAC', nome: 'Instituto de Cultura, Desenvolvimento Educacional, Promoção Humana e Ação Comunitária' },
    { codigo: 'BANCA-041', sigla: 'RBO', nome: 'RBO Assessoria Pública e Projetos Municipais' },
    { codigo: 'BANCA-042', sigla: 'SHDIAS', nome: 'SHDias Consultoria e Assessoria' },
    { codigo: 'BANCA-043', sigla: 'INTEGRI', nome: 'Integri Brasil' },
    { codigo: 'BANCA-044', sigla: 'OMNI', nome: 'Omni Concursos Públicos' },
    { codigo: 'BANCA-045', sigla: 'DIRECTA', nome: 'Directa Desenvolvimento Institucional e de Carreiras' },
    
    // Outras relevantes
    { codigo: 'BANCA-046', sigla: 'CONSULPAM', nome: 'Instituto Consulpam' },
    { codigo: 'BANCA-047', sigla: 'ADM&TEC', nome: 'Instituto de Administração e Tecnologia' },
    { codigo: 'BANCA-048', sigla: 'FADESP', nome: 'Fundação de Amparo e Desenvolvimento da Pesquisa' },
    { codigo: 'BANCA-049', sigla: 'CPCON', nome: 'Comissão Permanente de Concursos (UEPB)' },
    { codigo: 'BANCA-050', sigla: 'FUNDEP', nome: 'Fundação de Desenvolvimento da Pesquisa (UFMG)' },
    { codigo: 'BANCA-051', sigla: 'FUVEST', nome: 'Fundação Universitária para o Vestibular' },
    { codigo: 'BANCA-052', sigla: 'COMVEST', nome: 'Comissão Permanente para os Vestibulares da Unicamp' },
    { codigo: 'BANCA-053', sigla: 'UNINTER', nome: 'Centro Universitário Internacional' },
    { codigo: 'BANCA-054', sigla: 'GLOBAL', nome: 'Global Concursos' },
    { codigo: 'BANCA-055', sigla: 'MAKIYAMA', nome: 'Instituto Makiyama' }
];

export const instituicoesData = [
  { codigo: 'INST-001', sigla: 'SAEP', nome: 'Sistema de Avaliação da Educação Profissional' },
    { codigo: 'INST-002', sigla: 'PETROBRAS', nome: 'Petróleo Brasileiro S.A.' },
    { codigo: 'INST-003', sigla: 'TRANSPETRO', nome: 'Petrobras Transporte S.A.' },
    { codigo: 'INST-004', sigla: 'USP', nome: 'Universidade de São Paulo' },
    { codigo: 'INST-005', sigla: 'UNICAMP', nome: 'Universidade Estadual de Campinas' },
    { codigo: 'INST-006', sigla: 'UFRJ', nome: 'Universidade Federal do Rio de Janeiro' },
    { codigo: 'INST-007', sigla: 'IBGE', nome: 'Instituto Brasileiro de Geografia e Estatística' },
    { codigo: 'INST-008', sigla: 'EsPCEx', nome: 'Escola Preparatória de Cadetes do Exército' },
    { codigo: 'INST-009', sigla: 'ENEM', nome: 'Exame Nacional do Ensino Médio' },
    { codigo: 'INST-010', sigla: 'SENAI', nome: 'Serviço Nacional de Aprendizagem Industrial' },

    { codigo: 'INST-011', sigla: 'ITA', nome: 'Instituto Tecnológico de Aeronáutica' },
    { codigo: 'INST-012', sigla: 'IME', nome: 'Instituto Militar de Engenharia' },
    { codigo: 'INST-013', sigla: 'UNB', nome: 'Universidade de Brasília' },
    { codigo: 'INST-014', sigla: 'UFMG', nome: 'Universidade Federal de Minas Gerais' },
    { codigo: 'INST-015', sigla: 'UFRGS', nome: 'Universidade Federal do Rio Grande do Sul' },
    { codigo: 'INST-016', sigla: 'UFPR', nome: 'Universidade Federal do Paraná' },
    { codigo: 'INST-017', sigla: 'UFPE', nome: 'Universidade Federal de Pernambuco' },
    { codigo: 'INST-018', sigla: 'UFSC', nome: 'Universidade Federal de Santa Catarina' },
    { codigo: 'INST-019', sigla: 'UFBA', nome: 'Universidade Federal da Bahia' },
    { codigo: 'INST-020', sigla: 'UNESP', nome: 'Universidade Estadual Paulista "Júlio de Mesquita Filho"' },

    { codigo: 'INST-021', sigla: 'UTFPR', nome: 'Universidade Tecnológica Federal do Paraná' },
    { codigo: 'INST-022', sigla: 'UFSCar', nome: 'Universidade Federal de São Carlos' },
    { codigo: 'INST-023', sigla: 'UFABC', nome: 'Universidade Federal do ABC' },
    { codigo: 'INST-024', sigla: 'UERJ', nome: 'Universidade do Estado do Rio de Janeiro' },
    { codigo: 'INST-025', sigla: 'UFSM', nome: 'Universidade Federal de Santa Maria' },
    { codigo: 'INST-026', sigla: 'UFV', nome: 'Universidade Federal de Viçosa' },
    { codigo: 'INST-027', sigla: 'UFPel', nome: 'Universidade Federal de Pelotas' },
    { codigo: 'INST-028', sigla: 'UFPA', nome: 'Universidade Federal do Pará' },
    { codigo: 'INST-029', sigla: 'UEA', nome: 'Universidade do Estado do Amazonas' },
    { codigo: 'INST-030', sigla: 'IFSP', nome: 'Instituto Federal de Educação, Ciência e Tecnologia de São Paulo' },

    { codigo: 'INST-031', sigla: 'IFPR', nome: 'Instituto Federal do Paraná' },
    { codigo: 'INST-032', sigla: 'IFPE', nome: 'Instituto Federal de Pernambuco' },
    { codigo: 'INST-033', sigla: 'IFSC', nome: 'Instituto Federal de Santa Catarina' },
    { codigo: 'INST-034', sigla: 'IFCE', nome: 'Instituto Federal do Ceará' },
    { codigo: 'INST-035', sigla: 'INATEL', nome: 'Instituto Nacional de Telecomunicações' },
    { codigo: 'INST-036', sigla: 'FIOCRUZ', nome: 'Fundação Oswaldo Cruz' },
    { codigo: 'INST-037', sigla: 'POLI-USP', nome: 'Escola Politécnica da Universidade de São Paulo' },
    { codigo: 'INST-038', sigla: 'MAUÁ', nome: 'Universidade Mauá de Tecnologia' },
    { codigo: 'INST-039', sigla: 'FEI', nome: 'Centro Universitário FEI' },
    { codigo: 'INST-040', sigla: 'ETEC', nome: 'Escolas Técnicas Estaduais (ETEC - São Paulo)' },

    { codigo: 'INST-041', sigla: 'CEFET', nome: 'Centro Federal de Educação Tecnológica (CEFET)' },
    { codigo: 'INST-042', sigla: 'SENAC', nome: 'Serviço Nacional de Aprendizagem Comercial' },
    { codigo: 'INST-043', sigla: 'INSPER', nome: 'Insper Instituto de Ensino e Pesquisa' },
    { codigo: 'INST-044', sigla: 'FGV', nome: 'Fundação Getulio Vargas' },
    { codigo: 'INST-045', sigla: 'PUC-SP', nome: 'Pontifícia Universidade Católica de São Paulo' },
    { codigo: 'INST-046', sigla: 'PUC-RIO', nome: 'Pontifícia Universidade Católica do Rio de Janeiro' },
    { codigo: 'INST-047', sigla: 'MACKENZIE', nome: 'Universidade Presbiteriana Mackenzie' },
    { codigo: 'INST-048', sigla: 'ESC-NAVAL', nome: 'Escola Naval — Marinha do Brasil' },
    { codigo: 'INST-049', sigla: 'AMAN', nome: 'Academia Militar das Agulhas Negras' },
    { codigo: 'INST-050', sigla: 'EPCAR', nome: 'Escola Preparatória de Cadetes do Ar' },

    { codigo: 'INST-051', sigla: 'UFF', nome: 'Universidade Federal Fluminense' },
    { codigo: 'INST-052', sigla: 'UFG', nome: 'Universidade Federal de Goiás' },
    { codigo: 'INST-053', sigla: 'UFRN', nome: 'Universidade Federal do Rio Grande do Norte' },
    { codigo: 'INST-054', sigla: 'UFAM', nome: 'Universidade Federal do Amazonas' },
    { codigo: 'INST-055', sigla: 'UFAL', nome: 'Universidade Federal de Alagoas' },
    { codigo: 'INST-056', sigla: 'UFS', nome: 'Universidade Federal de Sergipe' },
    { codigo: 'INST-057', sigla: 'UFT', nome: 'Universidade Federal do Tocantins' },
    { codigo: 'INST-058', sigla: 'UFMS', nome: 'Universidade Federal de Mato Grosso do Sul' },
    { codigo: 'INST-059', sigla: 'UFMT', nome: 'Universidade Federal de Mato Grosso' },
    { codigo: 'INST-060', sigla: 'UFRRJ', nome: 'Universidade Federal Rural do Rio de Janeiro' },

    { codigo: 'INST-061', sigla: 'UFRB', nome: 'Universidade Federal do Recôncavo da Bahia' },
    { codigo: 'INST-062', sigla: 'UNIFESP', nome: 'Universidade Federal de São Paulo' },
    { codigo: 'INST-063', sigla: 'UDESC', nome: 'Universidade do Estado de Santa Catarina' },
    { codigo: 'INST-064', sigla: 'UEM', nome: 'Universidade Estadual de Maringá' },
    { codigo: 'INST-065', sigla: 'UEL', nome: 'Universidade Estadual de Londrina' },
    { codigo: 'INST-066', sigla: 'UEMG', nome: 'Universidade do Estado de Minas Gerais' },
    { codigo: 'INST-067', sigla: 'UNIRIO', nome: 'Universidade Federal do Estado do Rio de Janeiro' },
    { codigo: 'INST-068', sigla: 'UNICAP', nome: 'Universidade Católica de Pernambuco' },
    { codigo: 'INST-069', sigla: 'UFOPA', nome: 'Universidade Federal do Oeste do Pará' },
    { codigo: 'INST-070', sigla: 'IFRJ', nome: 'Instituto Federal do Rio de Janeiro' },

    { codigo: 'INST-071', sigla: 'IFBA', nome: 'Instituto Federal da Bahia' },
    { codigo: 'INST-072', sigla: 'IFTO', nome: 'Instituto Federal do Tocantins' },
    { codigo: 'INST-073', sigla: 'IFAM', nome: 'Instituto Federal do Amazonas' },
    { codigo: 'INST-074', sigla: 'UNIVALI', nome: 'Universidade do Vale do Itajaí' },
    { codigo: 'INST-075', sigla: 'UNIVESP', nome: 'Universidade Virtual do Estado de São Paulo' },
    { codigo: 'INST-076', sigla: 'UNIVAP', nome: 'Universidade do Vale do Paraíba' },
    { codigo: 'INST-077', sigla: 'EMBRAPA', nome: 'Empresa Brasileira de Pesquisa Agropecuária' },
    { codigo: 'INST-078', sigla: 'INMETRO', nome: 'Instituto Nacional de Metrologia, Qualidade e Tecnologia' },
    { codigo: 'INST-079', sigla: 'ANEEL', nome: 'Agência Nacional de Energia Elétrica' },
    { codigo: 'INST-080', sigla: 'ANTT', nome: 'Agência Nacional de Transportes Terrestres' },

    { codigo: 'INST-081', sigla: 'ANAC', nome: 'Agência Nacional de Aviação Civil' },
    { codigo: 'INST-082', sigla: 'ANVISA', nome: 'Agência Nacional de Vigilância Sanitária' },
    { codigo: 'INST-083', sigla: 'IBAMA', nome: 'Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis' },
    { codigo: 'INST-084', sigla: 'DNIT', nome: 'Departamento Nacional de Infraestrutura de Transportes' },
    { codigo: 'INST-085', sigla: 'RECEITA', nome: 'Receita Federal do Brasil' },
    { codigo: 'INST-086', sigla: 'PF', nome: 'Polícia Federal' },
    { codigo: 'INST-087', sigla: 'PRF', nome: 'Polícia Rodoviária Federal' },
    { codigo: 'INST-088', sigla: 'TRT-2', nome: 'Tribunal Regional do Trabalho da 2ª Região' },
    { codigo: 'INST-089', sigla: 'TRF-1', nome: 'Tribunal Regional Federal da 1ª Região' },
    { codigo: 'INST-090', sigla: 'TCU', nome: 'Tribunal de Contas da União' },

    { codigo: 'INST-091', sigla: 'MEC', nome: 'Ministério da Educação' },
    { codigo: 'INST-092', sigla: 'BNDES', nome: 'Banco Nacional de Desenvolvimento Econômico e Social' },
    { codigo: 'INST-093', sigla: 'BB', nome: 'Banco do Brasil' },
    { codigo: 'INST-094', sigla: 'CAIXA', nome: 'Caixa Econômica Federal' },
    { codigo: 'INST-095', sigla: 'CORREIOS', nome: 'Empresa Brasileira de Correios e Telégrafos' },
    { codigo: 'INST-096', sigla: 'ELETROBRAS', nome: 'Centrais Elétricas Brasileiras S.A. (Eletrobras)' },
    { codigo: 'INST-097', sigla: 'CAPES', nome: 'Coordenação de Aperfeiçoamento de Pessoal de Nível Superior' },
    { codigo: 'INST-098', sigla: 'INEP', nome: 'Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira' },
    { codigo: 'INST-099', sigla: 'UEPA', nome: 'Universidade do Estado do Pará' },
    { codigo: 'INST-100', sigla: 'ABIN', nome: 'Agência Brasileira de Inteligência' },

    { codigo: 'INST-101', sigla: 'UFJF', nome: 'Universidade Federal de Juiz de Fora' },
    { codigo: 'INST-102', sigla: 'UFU', nome: 'Universidade Federal de Uberlândia' },
    { codigo: 'INST-103', sigla: 'UFLA', nome: 'Universidade Federal de Lavras' },
    { codigo: 'INST-104', sigla: 'UNIFEI', nome: 'Universidade Federal de Itajubá' },
    { codigo: 'INST-105', sigla: 'UFOP', nome: 'Universidade Federal de Ouro Preto' },
    { codigo: 'INST-106', sigla: 'UFES', nome: 'Universidade Federal do Espírito Santo' },
    { codigo: 'INST-107', sigla: 'UENF', nome: 'Universidade Estadual do Norte Fluminense Darcy Ribeiro' },
    { codigo: 'INST-108', sigla: 'UERN', nome: 'Universidade do Estado do Rio Grande do Norte' },
    { codigo: 'INST-109', sigla: 'UECE', nome: 'Universidade Estadual do Ceará' },
    { codigo: 'INST-110', sigla: 'UVA', nome: 'Universidade Estadual Vale do Acaraú' },

    { codigo: 'INST-111', sigla: 'UFCG', nome: 'Universidade Federal de Campina Grande' },
    { codigo: 'INST-112', sigla: 'UFPB', nome: 'Universidade Federal da Paraíba' },
    { codigo: 'INST-113', sigla: 'UFPI', nome: 'Universidade Federal do Piauí' },
    { codigo: 'INST-114', sigla: 'UFMA', nome: 'Universidade Federal do Maranhão' },
    { codigo: 'INST-115', sigla: 'UNIFAP', nome: 'Universidade Federal do Amapá' },
    { codigo: 'INST-116', sigla: 'UNIR', nome: 'Universidade Federal de Rondônia' },
    { codigo: 'INST-117', sigla: 'UFRR', nome: 'Universidade Federal de Roraima' },
    { codigo: 'INST-118', sigla: 'UFAC', nome: 'Universidade Federal do Acre' },
    { codigo: 'INST-119', sigla: 'UNILA', nome: 'Universidade Federal da Integração Latino-Americana' },
    { codigo: 'INST-120', sigla: 'UNILAB', nome: 'Universidade da Integração Internacional da Lusofonia Afro-Brasileira' },

    { codigo: 'INST-121', sigla: 'IFMG', nome: 'Instituto Federal de Minas Gerais' },
    { codigo: 'INST-122', sigla: 'IFSUDESTE', nome: 'Instituto Federal do Sudeste de Minas Gerais' },
    { codigo: 'INST-123', sigla: 'IFNMG', nome: 'Instituto Federal do Norte de Minas Gerais' },
    { codigo: 'INST-124', sigla: 'IFGO', nome: 'Instituto Federal de Goiás' },
    { codigo: 'INST-125', sigla: 'IFG', nome: 'Instituto Federal Goiano' },
    { codigo: 'INST-126', sigla: 'IFMT', nome: 'Instituto Federal de Mato Grosso' },
    { codigo: 'INST-127', sigla: 'IFMS', nome: 'Instituto Federal de Mato Grosso do Sul' },
    { codigo: 'INST-128', sigla: 'IFRO', nome: 'Instituto Federal de Rondônia' },
    { codigo: 'INST-129', sigla: 'IFRR', nome: 'Instituto Federal de Roraima' },
    { codigo: 'INST-130', sigla: 'IFAC', nome: 'Instituto Federal do Acre' },

    { codigo: 'INST-131', sigla: 'IFMA', nome: 'Instituto Federal do Maranhão' },
    { codigo: 'INST-132', sigla: 'IFPI', nome: 'Instituto Federal do Piauí' },
    { codigo: 'INST-133', sigla: 'IFSUL', nome: 'Instituto Federal Sul-rio-grandense' },
    { codigo: 'INST-134', sigla: 'IFFAR', nome: 'Instituto Federal Farroupilha' },
    { codigo: 'INST-135', sigla: 'IFC', nome: 'Instituto Federal Catarinense' },
    { codigo: 'INST-136', sigla: 'IFTM', nome: 'Instituto Federal do Triângulo Mineiro' },
    { codigo: 'INST-137', sigla: 'IFSERTAOPE', nome: 'Instituto Federal do Sertão Pernambucano' },
    { codigo: 'INST-138', sigla: 'IFS', nome: 'Instituto Federal de Sergipe' },
    { codigo: 'INST-139', sigla: 'IFPB', nome: 'Instituto Federal da Paraíba' },
    { codigo: 'INST-140', sigla: 'IFRN', nome: 'Instituto Federal do Rio Grande do Norte' },

    { codigo: 'INST-141', sigla: 'FATEC', nome: 'Faculdades de Tecnologia do Estado de São Paulo' },
    { codigo: 'INST-142', sigla: 'CEETEPS', nome: 'Centro Estadual de Educação Tecnológica Paula Souza' },
    { codigo: 'INST-143', sigla: 'SENAT', nome: 'Serviço Nacional de Aprendizagem do Transporte' },
    { codigo: 'INST-144', sigla: 'SENAR', nome: 'Serviço Nacional de Aprendizagem Rural' },
    { codigo: 'INST-145', sigla: 'SENAC-TECH', nome: 'SENAC – Educação Profissional Tecnológica' },
    { codigo: 'INST-146', sigla: 'CEFET-MG', nome: 'Centro Federal de Educação Tecnológica de Minas Gerais' },
    { codigo: 'INST-147', sigla: 'CEFET-RJ', nome: 'Centro Federal de Educação Tecnológica Celso Suckow da Fonseca' },
    { codigo: 'INST-148', sigla: 'FAETEC', nome: 'Fundação de Apoio à Escola Técnica do Estado do Rio de Janeiro' },
    { codigo: 'INST-149', sigla: 'ETEC-TEC', nome: 'Escolas Técnicas Industriais Estaduais' },
    { codigo: 'INST-150', sigla: 'CPS', nome: 'Centro Paula Souza' },

    { codigo: 'INST-151', sigla: 'CNEN', nome: 'Comissão Nacional de Energia Nuclear' },
    { codigo: 'INST-152', sigla: 'CTA', nome: 'Departamento de Ciência e Tecnologia Aeroespacial' },
    { codigo: 'INST-153', sigla: 'IPEA', nome: 'Instituto de Pesquisa Econômica Aplicada' },
    { codigo: 'INST-154', sigla: 'INPE', nome: 'Instituto Nacional de Pesquisas Espaciais' },
    { codigo: 'INST-155', sigla: 'INT', nome: 'Instituto Nacional de Tecnologia' },
    { codigo: 'INST-156', sigla: 'CPRM', nome: 'Serviço Geológico do Brasil' },
    { codigo: 'INST-157', sigla: 'FURNAS', nome: 'Furnas Centrais Elétricas S.A.' },
    { codigo: 'INST-158', sigla: 'CHESF', nome: 'Companhia Hidro Elétrica do São Francisco' },
    { codigo: 'INST-159', sigla: 'ELETRONUCLEAR', nome: 'Eletrobras Termonuclear S.A.' },
    { codigo: 'INST-160', sigla: 'SERPRO', nome: 'Serviço Federal de Processamento de Dados' },

    { codigo: 'INST-161', sigla: 'DATAPREV', nome: 'Empresa de Tecnologia e Informações da Previdência' },
    { codigo: 'INST-162', sigla: 'FINEP', nome: 'Financiadora de Estudos e Projetos' },
    { codigo: 'INST-163', sigla: 'CNPQ', nome: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico' },
    { codigo: 'INST-164', sigla: 'BASA', nome: 'Banco da Amazônia S.A.' },
    { codigo: 'INST-165', sigla: 'BNB', nome: 'Banco do Nordeste do Brasil S.A.' },
    { codigo: 'INST-166', sigla: 'SUFRAMA', nome: 'Superintendência da Zona Franca de Manaus' },
    { codigo: 'INST-167', sigla: 'SUDENE', nome: 'Superintendência do Desenvolvimento do Nordeste' },
    { codigo: 'INST-168', sigla: 'SUDAM', nome: 'Superintendência do Desenvolvimento da Amazônia' },
    { codigo: 'INST-169', sigla: 'DNPM', nome: 'Departamento Nacional de Produção Mineral' },
    { codigo: 'INST-170', sigla: 'ANP', nome: 'Agência Nacional do Petróleo, Gás Natural e Biocombustíveis' },

    { codigo: 'INST-171', sigla: 'ANEEL-TECH', nome: 'Escola de Regulação da Agência Nacional de Energia Elétrica' },
    { codigo: 'INST-172', sigla: 'ESAF', nome: 'Escola de Administração Fazendária' },
    { codigo: 'INST-173', sigla: 'ENAP', nome: 'Escola Nacional de Administração Pública' },
    { codigo: 'INST-174', sigla: 'ESPCEX-SAÚDE', nome: 'Escola de Saúde do Exército Brasileiro' },
    { codigo: 'INST-175', sigla: 'EAGS', nome: 'Escola de Especialistas de Aeronáutica' }
];